### ISSUE TITLE
[bug] over max not checking

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#11]
i can storage blocks over max limit
blocks disappeared from inventory

**Comment by VoChiDanh** [comment]
What's your plugin version and server version?

**Comment by makegodhere** [comment]
> What's your plugin version and server version?

2.2.1
paper 1.21.3

![image](https://github.com/user-attachments/assets/cc555394-a5a6-4305-835f-8054e4085c30)

![image](https://github.com/user-attachments/assets/ec9ae73b-34bd-4270-a3c6-68554015c6ea)

after right click - all stone disappered
no message about limits

**Comment by VoChiDanh** [comment]
Fixed on next build

**Comment by VoChiDanh** [comment]
[Download DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12367268023/artifacts/2330188048)

**Comment by makegodhere** [comment]
> Fixed on next build

![image](https://github.com/user-attachments/assets/ee116003-ec6c-4c4d-9bd7-a4f68721d9d7)

wrong message - deposited only 10 stone - 2250 in chat

**Comment by VoChiDanh** [comment]
Oops 😬

**Comment by VoChiDanh** [comment]
Fixed on devbuild

**Comment by VoChiDanh** [comment]
[Download](https://github.com/VoChiDanh/Storage/actions/runs/12372311748/artifacts/2331507987)

**Comment by makegodhere** [comment]
> [Download](https://github.com/VoChiDanh/Storage/actions/runs/12372311748/artifacts/2331507987)

fixed

**Comment by makegodhere** [comment]
and this 
if store by right click - all good - right number in chat
but if left click and write 10 to chat - wrong number in chat

![image](https://github.com/user-attachments/assets/0018ebd0-a605-4c0e-b204-900f3c0a1339)

**Comment by VoChiDanh** [comment]
[DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12393464635/artifacts/2337540281)
