### ISSUE TITLE
[suggestion] get all from storage - fill inventory auto

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#15]
on right click get all from storage - fill inventory to full and send messagee how much getting blocks from storage
for now - just error message in chat
![image](https://github.com/user-attachments/assets/de0e61f8-aac3-4f59-8b35-60a9862f7eac)
![image](https://github.com/user-attachments/assets/7a353b1b-d4bb-4279-92a9-8d7212273414)

**Comment by VoChiDanh** [comment]
Done in next devbuild

**Comment by VoChiDanh** [comment]
[Download DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12367268023/artifacts/2330188048)

**Comment by makegodhere** [comment]
![image](https://github.com/user-attachments/assets/7615d067-085b-41ec-ae5f-18a1db98c147)

not getting to fill 17 stone to 64

**Comment by VoChiDanh** [comment]
Ye, not included that situation

**Comment by VoChiDanh** [comment]
Note and will do on next build :')

**Comment by VoChiDanh** [comment]
uh added on devbuild but idk if it work or not (I code after wake up and my brain not working well xD)
