### ISSUE TITLE
[bug] storage toggle off not fully functional

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#16]
if player inventory full and storage toggle off - blocks still move to storage - not drops on a ground
if player inventory not full - storage toggle off works as expected

**Comment by VoChiDanh** [comment]
report everything and I'll work again as soon as I can, thanks

**Comment by VoChiDanh** [comment]
i don't know but this working normal with mine, do you have any plugin related to autopickup or something?

**Comment by makegodhere** [comment]
toggle off
![image](https://github.com/user-attachments/assets/a9292b32-7905-4f9e-a568-de1a3fc85e78)

full inventory
![image](https://github.com/user-attachments/assets/6a9d7b6d-f679-4532-949b-24ee50042572)

break block (dirt for example) - all inventory move to storage
![image](https://github.com/user-attachments/assets/a4066270-a982-40fa-8118-3b84a98284b3)

**Comment by VoChiDanh** [comment]
ok, should fix on next build

**Comment by VoChiDanh** [comment]
[DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12393464635/artifacts/2337540281)
