### ISSUE TITLE
[bug] cannot craft black panel - not move to inventory

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#24]
cannot craft black panel - not moving to inventory

![image](https://github.com/user-attachments/assets/e717f774-b9ef-42cc-96a1-c2a4427bb087)

**Comment by VoChiDanh** [comment]
Can you explain more?

**Comment by makegodhere** [comment]
[Запись экрана от 2024-12-19 16-39-12.webm](https://github.com/user-attachments/assets/12813932-ff93-4a2c-a557-821089025b4b)

**Comment by VoChiDanh** [comment]
it is work if my plugin removed

**Comment by makegodhere** [comment]
> it is work if my plugin removed

sory - problem on another plugin
