### ISSUE TITLE
[bug] Withdraw full inventory

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#25]
![image](https://github.com/user-attachments/assets/5df26522-1d8b-4014-ac8f-4ac672cbe8e6)
![image](https://github.com/user-attachments/assets/705aaf35-baa5-46d2-8768-40b6b80169b8)
![image](https://github.com/user-attachments/assets/02251cfb-022a-4c8a-a2ac-bed91e7d1e91)
![image](https://github.com/user-attachments/assets/67c94c7a-7527-4187-a123-6b9548bc2c99)

**Comment by VoChiDanh** [comment]
[Download DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12445929907/artifacts/2351869902)
