### ISSUE TITLE
[suggestion] allow break block on full storage

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#26]
![image](https://github.com/user-attachments/assets/665b7b32-3cf4-492f-834d-0b10979517b7)

when mass break block - storage toggle on prevent break block on full storage
you need to toggle off each time - very uncomfortable mine mass blocks

need to ignore toggle on when break block wich fulling in storage

**Comment by VoChiDanh** [comment]
> ![image](https://private-user-images.githubusercontent.com/28805838/397512014-665b7b32-3cf4-492f-834d-0b10979517b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY5ODYsIm5iZiI6MTczNDc4NjY4NiwicGF0aCI6Ii8yODgwNTgzOC8zOTc1MTIwMTQtNjY1YjdiMzItM2NmNC00OTJmLTgzNGQtMGIxMDk3OTUxN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTRlNTU4MDgxNmVlZjU2MjIwNTNlMDk4OGYwMDg4YTMzZDhmODk2ZjY3MzkzNzE4YWIxYTljOGVhNWE2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.60pqdA2RzKiPzxWh6s3qOgPqLZDw5BGiGwRFA8Zp7Rs)
> 
> when mass break block - storage toggle on prevent break block on full storage you need to toggle off each time - very uncomfortable mine mass blocks
> 
> need to ignore toggle on when break block wich fulling in storage

Sorry but I don't understand what do you mean

**Comment by makegodhere** [comment]
> > ![image](https://private-user-images.githubusercontent.com/28805838/397512014-665b7b32-3cf4-492f-834d-0b10979517b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY5ODYsIm5iZiI6MTczNDc4NjY4NiwicGF0aCI6Ii8yODgwNTgzOC8zOTc1MTIwMTQtNjY1YjdiMzItM2NmNC00OTJmLTgzNGQtMGIxMDk3OTUxN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTRlNTU4MDgxNmVlZjU2MjIwNTNlMDk4OGYwMDg4YTMzZDhmODk2ZjY3MzkzNzE4YWIxYTljOGVhNWE2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.60pqdA2RzKiPzxWh6s3qOgPqLZDw5BGiGwRFA8Zp7Rs)
> > when mass break block - storage toggle on prevent break block on full storage you need to toggle off each time - very uncomfortable mine mass blocks
> > need to ignore toggle on when break block wich fulling in storage
> 
> Sorry but I don't understand what do you mean

need to ignore toggle on when block in storage is full
if block count in storage is max need to drop block on break on a ground
because when you mining in mine you will break a lot of blocks and switch toggle on\off on every block very uncomfortable
this is just user-experience moment

**Comment by VoChiDanh** [comment]
So you want add 1 option for send a full message can be toggle on/off ?

**Comment by makegodhere** [comment]
> So you want add 1 option for send a full message can be toggle on/off ?

want to allow break block when storage is full and drop block on a ground
if toggle is on and block storage is full - drop block on a ground like then toggle is off

**Comment by VoChiDanh** [comment]
ah ah ok ok

**Comment by VoChiDanh** [comment]
[Download DevBuild](https://github.com/VoChiDanh/Storage/actions/runs/12445929907/artifacts/2351869902)

**Comment by makegodhere** [comment]
![image](https://github.com/user-attachments/assets/1aa0415e-0ad7-4be9-904d-ad690f4dc43c)

now allow block break then toggle on - than good
but block doesnt drop

**Comment by VoChiDanh** [comment]
[Download](https://github.com/VoChiDanh/Storage/actions/runs/12460211034/artifacts/2354376815)

**Comment by makegodhere** [comment]
> [Download](https://github.com/VoChiDanh/Storage/actions/runs/12460211034/artifacts/2354376815)

working good thx

but new bug
![image](https://github.com/user-attachments/assets/04e025fa-672b-41b4-ac19-f0b62e02c4bf)
![image](https://github.com/user-attachments/assets/e9eb112b-6858-4125-b8b1-ef356609a080)
[Запись экрана от 2024-12-23 12-53-40.webm](https://github.com/user-attachments/assets/0d03a0cd-2092-4fce-a1d2-40de42c1fd09)

**Comment by VoChiDanh** [comment]
Wooo 🥲

**Comment by VoChiDanh** [comment]
> working good thx
> 
> but new bug all inventory disappear on break one block
> 
> ![image](https://private-user-images.githubusercontent.com/28805838/398123735-04e025fa-672b-41b4-ac19-f0b62e02c4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTg1OTEsIm5iZiI6MTczNDk1ODI5MSwicGF0aCI6Ii8yODgwNTgzOC8zOTgxMjM3MzUtMDRlMDI1ZmEtNjcyYi00MWI0LWFjMTktZjBiNjJlMDJjNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyNTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlODIwYTdlYWJiN2UyNGU2ZjlkNGEyYTk5MTM3MzZiYmQ2MDExNDkzOGUwNjIzMDM0YTQ1NTllZjgwMTE2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Js8tZ64fPgSEger152c4ViCsZ1LbtNJ3eCcOeBQRV2Y) ![image](https://private-user-images.githubusercontent.com/28805838/398123809-e9eb112b-6858-4125-b8b1-ef356609a080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTg1OTEsIm5iZiI6MTczNDk1ODI5MSwicGF0aCI6Ii8yODgwNTgzOC8zOTgxMjM4MDktZTllYjExMmItNjg1OC00MTI1LWI4YjEtZWYzNTY2MDlhMDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyNTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmY0YzRjYWExZDNkNzU4MDY0YjNjZmI1ZjIyZmUzY2YyOTk0NjkzYzNmY2UxYzM2YzRhYzAzY2FjZGRjMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yZnp5_u5xRnG2OUTsP2yDipHOWAb_Ha7ofeeCJlczUQ)
> 
>  2024-12-23.12-53-40.webm

[Download](https://github.com/VoChiDanh/Storage/actions/runs/12467254589/artifacts/2355895903)
